import {
  addMovie,
  deleteMovie,
  editMovie,
  filteredMovies,
  getMovieByTitle,
  loadMovies,
  loadMoviesDefault,
  onClearSearch,
  moviesLoaded,
  getMovieById,
  updateGenres,
  moviesLoadedDefault,
  deleteMovieFromStore,
  addMovieInStore,
  editMovieInStore,
  getMovieBySearchString,
  moviePreview,
} from './movieAction';

export default {
  moviesLoaded,
  loadMovies,
  deleteMovie,
  addMovie,
  editMovie,
  getMovieByTitle,
  loadMoviesDefault,
  onClearSearch,
  filteredMovies,
  getMovieById,
  updateGenres,
  moviesLoadedDefault,
  deleteMovieFromStore,
  addMovieInStore,
  editMovieInStore,
  getMovieBySearchString,
  moviePreview,
};
